/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    // Placeholder routes - will be auto-generated when route files are created
    '/terms': { id: '/terms'; path: '/terms'; fullPath: '/terms'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/privacy': { id: '/privacy'; path: '/privacy'; fullPath: '/privacy'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/sign-in': { id: '/sign-in'; path: '/sign-in'; fullPath: '/sign-in'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/sign-up': { id: '/sign-up'; path: '/sign-up'; fullPath: '/sign-up'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/settings': { id: '/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/dashboard': { id: '/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/dashboard/billing': { id: '/dashboard/billing'; path: '/dashboard/billing'; fullPath: '/dashboard/billing'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/dashboard/teams': { id: '/dashboard/teams'; path: '/dashboard/teams'; fullPath: '/dashboard/teams'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/dashboard/teams/create': { id: '/dashboard/teams/create'; path: '/dashboard/teams/create'; fullPath: '/dashboard/teams/create'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/forgot-password': { id: '/forgot-password'; path: '/forgot-password'; fullPath: '/forgot-password'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/reset-password': { id: '/reset-password'; path: '/reset-password'; fullPath: '/reset-password'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/verify-email': { id: '/verify-email'; path: '/verify-email'; fullPath: '/verify-email'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/team-invite': { id: '/team-invite'; path: '/team-invite'; fullPath: '/team-invite'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/sso/google': { id: '/sso/google'; path: '/sso/google'; fullPath: '/sso/google'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/sso/google/': { id: '/sso/google/'; path: '/sso/google/'; fullPath: '/sso/google/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/sso/google/callback': { id: '/sso/google/callback'; path: '/sso/google/callback'; fullPath: '/sso/google/callback'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/dashboard/': { id: '/dashboard/'; path: '/dashboard/'; fullPath: '/dashboard/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/settings/': { id: '/settings/'; path: '/settings/'; fullPath: '/settings/'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/settings/security': { id: '/settings/security'; path: '/settings/security'; fullPath: '/settings/security'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
    '/settings/sessions': { id: '/settings/sessions'; path: '/settings/sessions'; fullPath: '/settings/sessions'; preLoaderRoute: typeof IndexImport; parentRoute: typeof rootRoute }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/terms': typeof IndexRoute
  '/privacy': typeof IndexRoute
  '/sign-in': typeof IndexRoute
  '/sign-up': typeof IndexRoute
  '/settings': typeof IndexRoute
  '/settings/': typeof IndexRoute
  '/settings/security': typeof IndexRoute
  '/settings/sessions': typeof IndexRoute
  '/dashboard': typeof IndexRoute
  '/dashboard/': typeof IndexRoute
  '/dashboard/billing': typeof IndexRoute
  '/dashboard/teams': typeof IndexRoute
  '/dashboard/teams/create': typeof IndexRoute
  '/admin': typeof IndexRoute
  '/forgot-password': typeof IndexRoute
  '/reset-password': typeof IndexRoute
  '/verify-email': typeof IndexRoute
  '/team-invite': typeof IndexRoute
  '/sso/google': typeof IndexRoute
  '/sso/google/': typeof IndexRoute
  '/sso/google/callback': typeof IndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/terms': typeof IndexRoute
  '/privacy': typeof IndexRoute
  '/sign-in': typeof IndexRoute
  '/sign-up': typeof IndexRoute
  '/settings': typeof IndexRoute
  '/settings/': typeof IndexRoute
  '/settings/security': typeof IndexRoute
  '/settings/sessions': typeof IndexRoute
  '/dashboard': typeof IndexRoute
  '/dashboard/': typeof IndexRoute
  '/dashboard/billing': typeof IndexRoute
  '/dashboard/teams': typeof IndexRoute
  '/dashboard/teams/create': typeof IndexRoute
  '/admin': typeof IndexRoute
  '/forgot-password': typeof IndexRoute
  '/reset-password': typeof IndexRoute
  '/verify-email': typeof IndexRoute
  '/team-invite': typeof IndexRoute
  '/sso/google': typeof IndexRoute
  '/sso/google/': typeof IndexRoute
  '/sso/google/callback': typeof IndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/terms' | '/privacy' | '/sign-in' | '/sign-up' | '/settings' | '/settings/' | '/settings/security' | '/settings/sessions' | '/dashboard' | '/dashboard/' | '/dashboard/billing' | '/dashboard/teams' | '/dashboard/teams/create' | '/admin' | '/forgot-password' | '/reset-password' | '/verify-email' | '/team-invite' | '/sso/google' | '/sso/google/' | '/sso/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/terms' | '/privacy' | '/sign-in' | '/sign-up' | '/settings' | '/settings/' | '/settings/security' | '/settings/sessions' | '/dashboard' | '/dashboard/' | '/dashboard/billing' | '/dashboard/teams' | '/dashboard/teams/create' | '/admin' | '/forgot-password' | '/reset-password' | '/verify-email' | '/team-invite' | '/sso/google' | '/sso/google/' | '/sso/google/callback'
  id: '__root__' | '/' | '/terms' | '/privacy' | '/sign-in' | '/sign-up' | '/settings' | '/settings/' | '/settings/security' | '/settings/sessions' | '/dashboard' | '/dashboard/' | '/dashboard/billing' | '/dashboard/teams' | '/dashboard/teams/create' | '/admin' | '/forgot-password' | '/reset-password' | '/verify-email' | '/team-invite' | '/sso/google' | '/sso/google/' | '/sso/google/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
